services:
  chat-ai-bot:
    build: .
    image: chat-ai-bot:latest
    container_name: chat-ai-bot
    restart: always
    ports:
      - "8091:8091"
    env_file:
      - .env
    extra_hosts:
      - "${VAULT_HOST}:${VAULT_HOST_IP}"
